---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: prometheus-access
  namespace: monitoring
spec:
  ports:
  - name: "9090"
    port: 9090
    nodePort: 30088
  selector:
    app: prometheus
  type: NodePort
