---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: grafana-access
  namespace: monitoring
spec:
  ports:
  - name: "3000"
    port: 3000
    nodePort: 30099
  selector:
    app: grafana
  type: NodePort
